version: "3.2"
services:
  otel:
    image: amazon/aws-otel-collector:latest
    command: --config /config/collector-config.yml --log-level debug
    volumes:
      - ./otel:/config
    environment:
      AWS_ACCESS_KEY_ID: ${INTEG_TEST_AWS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${INTEG_TEST_AWS_KEY_SECRET}
    ports:
      - '55680:55680'
      - '30080:30080'
