version: "3.2"
services:
  otel:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: --config /config/collector-config.yml --log-level debug
    volumes:
      - ./otel:/config
    environment:
      AWS_ACCESS_KEY_ID: ${ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      AWS_REGION: us-west-2
    ports:
      - '55680:55680'
      - '30080:30080'
      - '9464:9464'
